# Example workflow
# .github/workflows/example.yml

name: 'example oidc'
on:
  push:
    branches:
    - 'main'
jobs:
  run:
    name: 'example to list bucket contents'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
        uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: "https://iam.googleapis.com/projects/504579259344/locations/global/workloadIdentityPools/my-pool/providers/my-provider" # this is the output provider_name from the TF module
        service_account: "tsting@rbadawi-host-vpc.iam.gserviceaccount.com" # this is a SA email configured using the TF module with access to YOUR-GCS-BUCKET
        access_token_lifetime: 300s
        token_format: access_token
    - id: 'list'
      run: |-
        curl https://storage.googleapis.com/storage/v1/b/kamar-tf-state/o \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"